### ISSUE TITLE
Придумать отдельную нотацию для количества аргументов

### ISSUE THREAD

**Issue by miripiruni** [pepelsbey/zen-coding-snippets#1]
bdrz:4
bdrz:3
bdrz:2

4-3-2 это уж точно не значения. И, по-моему, не логично их писать через двоеточия будто бы это значение: «z-index:1;»
Нужно придумать сабж.

**Comment by pepelsbey** [comment]
Пусть тот, кто скажет, что 4-3-2 — это свойство первым бросит в меня камень. Это _тип_ значения, тоже самое справедливо и для других свойств, принимающих комбинированные значения (padding, margin). На самом деле, это проблема статических снипетов, это всё легко реализуется для динамических снипетов, которые предлагает Хаяку.

Я бы скорее дропнул эти сокращения, они несколько сомнительны и уж тем более не так часто употребимы. А если употребимы то не на той скорости, для которой нужен подобный снипет.

**Comment by miripiruni** [comment]
Стоп.
Я призываю отделить случаи, которые у тебя в кашу:
1. свойство:значение
2. свойство:количество_аргументов

Это должны быть разные нотации, а не одинаковые пары через двоеточие.

**Comment by kizu** [comment]
Я за то, чтобы вообще дропнуть сниппеты для количества аргументов.

Для Хаяку я думал над таким синтаксисом:

```
m0 — margin: 0;
m00 — margin: 0 ${1:0};
m010 — margin: 0 10px;
m000 — margin: 0 0 ${1:0};
m00.1 — margin: 0 0 .1em;
```

и т.д., я для себя аргументировал это тем, что не бывает свойств, в которых надо было бы задавать значение с несколькими нолями. Но в итоге, мне и такой вариант не нравится из-за неочевидного синтаксиса и возможных конфликтов.

Потому — лучше это вообще выкинуть т.к. в синтаксисе с дополнительным символом и числом мы мало выигрываем, а если во всех плейсхолдерах будет что-то вбито (1px 2px 3px, а не 0 0 3px), то мы и вовсе ничего не выигрываем.

**Comment by miripiruni** [comment]
m0 — отличная нотация. А в списке Вадима нужно либо придерживаться её, либо выкинуть подобные случаи чтобы не путали со значениями.

**Comment by pepelsbey** [comment]
Нотации m:4 и p:4 давно дропнуты, поэтому закрываю
