### ISSUE TITLE
Не хватает некоторых css-свойств

### ISSUE THREAD

**Issue by boronchiev** [pepelsbey/zen-coding-snippets#3]
border-spacing
border-top-image
border-right-image
border-bottom-image
border-left-image
border-corner-image
border-top-left-image
border-top-right-image
border-bottom-right-image
border-bottom-left-image

**Comment by pepelsbey** [comment]
Thanks for report! Fixed by bf7d455d88

**Comment by tonyganch** [comment]
Some more:

animation-fill-mode
perspective
perspective-origin
transform-style
box-align
box-direction
box-flex
box-flex-group
box-lines
box-ordinal-group
box-orient
box-pack
grid-columns
grid-rows
appearance
