### ISSUE TITLE
Добавить свойства

### ISSUE THREAD

**Issue by miripiruni** [pepelsbey/zen-coding-snippets#4]
Можешь посмотреть каких свойств из этого списка нет в Zen Coding-е и какие актуальны и их стоит добавить? 
https://github.com/miripiruni/CSScomb/issues/135#issuecomment-9844245

**Comment by pepelsbey** [comment]
У меня такая политика, что я очень не хочу добавлять в сортировку свойства, которые не поддерживаются ни одним браузером (в основном, шрифтовые). В списке, насколько я понимаю, такие есть. И очень важно понять, как именно @tonyganch пришла к этому списку, ведь ещё [неделю назад](https://github.com/pepelsbey/zen-coding/issues/3#issuecomment-9643028) он был меньше.

Поэтому рисёч по потерянным свойствам запланирован, как скоро — зависит от того, какой приоритет ты этому выставишь. Главное — подобрать все новые MS-свойства, Flexbox, Grid и прочие новинки. Дело вечера-двух, не больше.

**Comment by miripiruni** [comment]
Алена говорит, что в списке те свойства, которые поддерживаются хотя бы одним браузером. Значит есть шанс, что их кто-то напишет. И надо сортировать и иметь сниппет.

**Comment by pepelsbey** [comment]
Внимание: откуда эти свойства взялись, какова методика? Мне же проверить нужно, а не просто добавить.

**Comment by miripiruni** [comment]
@tonyganch?

**Comment by miripiruni** [comment]
Протухло.
