### ISSUE TITLE
Свойства -moz-border-radius по отдельным углам

### ISSUE THREAD

**Issue by boronchiev** [pepelsbey/zen-coding-snippets#5]
Кажется, запись этих свойств неверна:

-moz-border-top-right-radius
-moz-border-bottom-right-radius
-moz-border-bottom-left-radius
-moz-border-top-left-radius

-moz-border-radius-topright
-moz-border-radius-bottomright
-moz-border-radius-bottomleft
-moz-border-radius-topleft

https://developer.mozilla.org/en-US/docs/CSS/border-top-left-radius#Browser_compatibility

**Comment by pepelsbey** [comment]
Спасибо!
